# 自动化构建/部署项目
# language: node_js
# node_js:
#   - 'stable'
# cache:
#   directories:
#     - node_modules
# env:
#   - CI=true
# script:
#   - npm run build:doc
# deplet:
#   provider:
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: docs
#   on:
#     branch: master

